### ISSUE TITLE
Character Backs render issue in v15

### ISSUE THREAD

**Issue by djrenren** [andymeneely/project-timber-wolf#1]
`character_backs.pdf` looks like the text is misplaced.  Also even if it was placed it looks like the graphics wouldn't have enough room for the text.
![oops](https://user-images.githubusercontent.com/634666/27980621-77b73c9a-6335-11e7-9649-c879d610d399.png)

**Comment by andymeneely** [comment]
Yeah I've redone these for the latest version. I'll put out another release. Sorry - I didn't realize anyone else was watching!

**Comment by djrenren** [comment]
Haha no worries, just going through trying to make my own.
