### ISSUE TITLE
[spoiler] End of mission 2: Fat 💲💲💲?

### ISSUE THREAD

**Issue by derekerdmann** [andymeneely/project-timber-wolf#3]
Finished mission 2, acquired $3k. Story says we went to prison, but we still have all the money we looted? Not sure when this would have been deposited in our offshore accounts. Might be a good way to introduce players to civil forfeiture laws.

**Comment by andymeneely** [comment]
Yep, it's in your offshore accounts. I'll double-check how the money comes into play.

**Comment by derekerdmann** [comment]
That totally makes sense for the game mechanics, just a little confusing during the flow of the story.

**Comment by andymeneely** [comment]
Clarified a bit in v16.0
